### PR TITLE
Feature/tim/kraken futures

### PR DESCRIPTION
**Pull request by elbart**
Add Basic KrakenFutures support (only orderbook so far)

### CODE REVIEW

**Comment by soulmachine** [comment]
Hi Tim,

Thanks for your great work! This is a big PR, I'd like to split it into 5 smaller PRs:

1. First, update the `crypto-market-type` library, as far as I see, kraken futures has two market types, `InverseSwap` and `InverseFuture`, for example https://futures.kraken.com/trade/futures/PI_XBTUSD is InverseSwap, https://futures.kraken.com/trade/futures/FI_XBTUSD_220225 is InverseFutre. After you submit this PR, I'll merge it and publish a newer `crypto-market-type` library
2. Second, implement `fetch_symbols()` and `fetch_markets()` for Kraken Futures in the `crypto-markets` library,  underneath it calls <https://futures.kraken.com/derivatives/api/v3/instruments>. Still, after you submit this PR, I'll merge it and publish a newer `crypto-markets` library
3. Implement the logic in `crypto-ws-client` library and I'll publish a newer version
4. Implement the logic in `crypto-crawler` using the newer `crypto-market-type`, `crypto-ws-client` and `crypto-markets`
5. Implement the logic in `crypto-msg-parser` library

**Comment by soulmachine** [comment]
Hi Tim,

Kraken Futures is supported by commit this https://github.com/soulmachine/crypto-crawler-rs/commit/6db007c5571852fc951f97f919dc10c63f3f0638 now

So I'm closing this PR

Thanks for your work, feel free to submit issues and PRs next time!

**Comment by elbart** [comment]
Hi Frank,

sorry for the delay. Frankly speaking I was a bit overwhelmed by the "overhead" for this PR and actually needed to finish the actual project I was working on. Sorry for being such unresponsive. I usually try to be more responsive :/

Also your change seems more adequate regarding how to actually implement the change.
Is this commit already on crates.io in the latest version of crypto-ws-rs?

Best regards and thanks for your great work!

Tim

**Comment by elbart** [comment]
Just saw that the latest versions seem to contain your mentionend changes! Thanks!

**Comment by soulmachine** [comment]
@elbart Does the new version meets your needs? For example,

* `carbonbot kraken inverse_future trade FI_XBTUSD_220624` can crawl tick-by-tick trade data of <https://futures.kraken.com/trade/futures/FI_XBTUSD_220624>
* `carbonbot kraken inverse_future trade` can crawl tick-by-tick trade data for all deliverable futures .
* `carbonbot kraken inverse_swap l2_event` can crawl tick-by-tick level2 orderbook data for all perpetual contracts.
* `carbonbot -h` to see help

**Comment by elbart** [comment]
@soulmachine All stuff I need currently works fine. Thanks for asking!

**Pull request closed without merging**
