### PR TITLE
Add update sequence IDs to OrderBookMsg

### PR DESCRIPTION
**Pull request by xermicus**
Currently the sequence / update IDs are not parsed from the Orderbook update events. Not all exchanges ship them, however I think they are actually very important (building algorithmic trading strategies without knowing about potential gaps in the data can lead to catastrophic failures). This PR tries to fix that in a non-invasive manner by adding the corresponding fields to the Orderbook Update Message as `Option<u64>`.

Note that some exchanges provide a checksum instead, which can also be used to verify integrity, which would be yet another addition I think would be best added in another PR.

For exchanges providing a sequence number for the whole update (instead of 1 for each update entry), the field `seq_first` is set and `seq_last` remains `None`.

### CODE REVIEW

**Comment by soulmachine** [comment]
In real world if you find missing sequence IDs, how do you deal with it? Most exchanges don't provide RESTful API to retrieve orderbook messages via sequence IDs, so there is no way to remedy the data.

In my understanding, if there are missing sequence IDs, then these messages are lost permanently, what's the point of adding `seq_first` and `seq_last`?

My way to deal with missing sequence IDs is to launch multiple instances of crawlers at different countries/regions, which will relieve the issue of missing messages a lot.

**Comment by xermicus** [comment]
I understand that the PR changes quite a bit of code (I couldn't see an easier / less noisy way to implement it). So, many thanks for your patience and review! 

Currently I use the sequence IDs to create contiguous time series from the data where I know there are no missing updates. In live trading I close all open orders and re-fetch snapshots ("cold reboot" the trade bot) on any data anomalies. But this can only be detected reliably by using the sequence numbers / trade IDs.

Having more than one data crawler instance may help but I don't think it fully solves the problem. For live trading having redundant sources of the same updates without having sequence numbers actually adds to the problem: What update (and in what order) do you feed to your trade bot if the updates you crawlers output diverge? 

My concern is how would you ensure the integrity of a local orderbook without these sequence numbers? For example if you miss the deletion update for the best ask (or mistakingly discard an update by wrongly thinking it was already supplied by a different crawler source) you incorrectly end up with a negative spread. And you wouldn't even know for how long the book was in that corrupt state..

I Hope I could explain a bit the reason for this PR.

**Comment by soulmachine** [comment]
Today after I see your scenario, I'm convinced that it is valuable to add sequence IDs to `OrderBookMsg`.

I suggest that we should change your current design a little bit. I prefer to change `seq_first` and `seq_last` to `seq_id` and `prev_seq_id`. Each orderbook message should have a unique `seq_id` and have `prev_seq_id` pointing to its former message, by this way all orderbook messages are linked together in a singly linked list. In your use case,  If you can not find `prev_seq_id` which means some messages are missing, you can restart your live trading bot.

* binance: assign `u` to `seq_id` and `pu` to `prev_seq_id`
* bithumb: assign `ver` to `seq_id` and None to `prev_seq_id`
* deribit: assign `change_id` to `seq_id` and `prev_change_id` to `prev_seq_id`
* huobi: assign `seqNum` to `seq_id` and `prevSeqNum` to `prev_seq_id` for spot, for contract markets assign `mrid` to `seq_id` and None to `prev_seq_id`
* kucoin: assign `sequence` or `sequenceStart` to `seq_id`, and None to `prev_seq_id`

I don't have time to check other exchanges yet, and you don't need to implement all exchanges, you can just implement the exchanges that you're using.

Please validate new fields in test cases under the `tests` folder, for example, `tests/binance.rs`, `tests/deribit.rs`, etc.

**Comment by xermicus** [comment]
Cool, I implemented it as you suggested it using `seq_id` and `prev_seq_id`.

As I quickly checked every exchange in the library I conclude that the following exchanges provide sequense ID information:
* binance
* bithumb
* deribit
* huobi
* kucoin
* gate
So I Implemented (and updated the corresponding tests) for these. For all other exchanges it is just set to `None` immediatly because they don't deliver this information.

**Comment by soulmachine** [comment]
Hi @xermicus , this is great job, thank you for making this happen!

**Comment by xermicus** [comment]
welcome!

**Pull request merged**
