### PR TITLE
carbonbot: allow filtering for symbols

### PR DESCRIPTION
**Pull request by xermicus**
See #2

### CODE REVIEW

**Comment by soulmachine** [comment]
Hi Cyrill, can we pass symbols through command line? Because different exchanges have different values for `SYMBOLS_BY_MATCH`, while they can share the same `SYMBOLS_BY_CMC`.

First, change the line

```rust
println!("Usage: carbonbot <exchange> <market_type> <msg_type>");
```

to 

```rust
println!("Usage: carbonbot <exchange> <market_type> <msg_type> [comma seperated_symbols]");
```

By this way, we don't need the `SYMBOLS_BY_MATCH` environment variable anymore.

Meanwhile,  can we rename `SYMBOLS_BY_CMC` to another name? I don't have good suggestions, but its currently name is not straightforward.

**Comment by xermicus** [comment]
Thanks for the feedback, changed the filter list to cmd arg.

I agree with `SYMBOLS_BY_CMC`. Actually after some consideration I think it is only confusing after all to have that feature, so I just decided removed it completely.

**Comment by soulmachine** [comment]
Thanks for the work!

**Comment by xermicus** [comment]
Welcome :-)

**Pull request merged**
